### ISSUE TITLE
Link from mail generates "Ungültiges Token"

### ISSUE THREAD

**Issue by design23** [psi-4ward/news4ward_comments#11]
Hi,

got a Cto 3.5.2 installation with news4ward + comments etc.
When a new comment is sent, the admin gets a notification via email with an "edit" link in it.
This link only generates the classic "Ungültiges Token" error message  (see screenshot). 
Bug or wrong configuration?
![bildschirmfoto 2015-11-12 um 10 40 45](https://cloud.githubusercontent.com/assets/6112308/11115238/664c0ddc-892a-11e5-9ee7-77a3de449567.png)

**Comment by psi-4ward** [comment]
Unsolveable problem.
Contao verifies the BE URLs using a token which gets generated on login so i can not put this token into the email.

@frontendschlampe, @aschempp do you have any ideas?

**Comment by design23** [comment]
Wow, thanks for the quick response!

I ran into this kinda stuff quite often... what is the problem there? It appears even when I'm already logged in.

**Comment by psi-4ward** [comment]
See the url of a working page, theres a `rt=1h2h3123h12` in the URI

**Comment by design23** [comment]
What do you mean with "working page"?

**Comment by aschempp** [comment]
Well this is intended by Contao. Make sure the link you receive is what you intend to do, so noone can send you a link and saying "this will edit your comment" but then the link will actually delete it.

**Comment by psi-4ward** [comment]
see `ref` in `/contao/main.php?do=article&ref=29a0e964`

**Comment by design23** [comment]
So there is no solution at all?
In this case that link is completely useless or am I missing something here?

**Comment by aschempp** [comment]
You're missing something: The popup is intended for security reasons. You should verify the link you clicked actually does what it is intended to do (edit a comment) before continuing the action.

**Comment by design23** [comment]
Oh okay... now I get it! The look and feel of this message just made me think it's an error. 
Thanks for you time, guys!
